mode: direct # events ingested directly into demo.sentry.io

browsers:
- remote: true
  browserName: chrome
  browserVersion: latest
  platformName: Windows 10
  param_display: chrome_windows
- remote: true
  browserName: chrome
  browserVersion: latest
  platformName: Windows 10
  param_display: fake_firefox_windows
  userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:139.0) Gecko/20100101 Firefox/139.0
## commenting out safari for now as it's not loading up empower-app as expected
## see `sauceLabsUrl`s in https://demo.sentry.io/issues/5275523263/?project=5390094
# - remote: true
#   browserName: safari
#   browserVersion: latest-1
#   platformName: OS X 10.13
#   param_display: safari_osx
## Adding in Chrome in place of safari just to produce more/enough data
- remote: true
  browserName: chrome
  browserVersion: latest
  platformName: Windows 10
  param_display: chrome_windows_2 
- remote: true
  browserName: chrome
  browserVersion: latest
  platformName: OS X 10.13
  param_display: chrome_osx

dsn: 'https://9802de20229e4afdaa0d60796cbb44d7@o87286.ingest.sentry.io/5390094'

# endpoints should NOT have "/" at the end
react_endpoint: https://empower-plant.com
nextjs_endpoint: https://nextjs.empower-plant.com
angular_endpoint: https://angular.empower-plant.com
vue_endpoint: https://application-monitoring-vue-dot-sales-engineering-sf.appspot.com
