name: Crons Demo job (runs every 5 min, sometimes randomly failing or taking too long)

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes 
    #- cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:
    
jobs:
  default-job:
    if: github.repository_owner == 'sentry-demos' # don't run in forks
    runs-on: ubuntu-latest
    #permissions:
    #  contents: 'read'
    #  id-token: 'write'
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Setup Sentry CLI
        uses: mathieu-bour/setup-sentry-cli@v1.3.0
        with:
          version: 2.17.4
          token: ${{ SECRETS.SENTRY_AUTH_TOKEN }} # from GitHub secrets

      - name: Run cron job script with `sentry-cli monitors run`
        run: |
          export SENTRY_DSN=https://16b1b593fa1c4c67b925cadb496a531b@o87286.ingest.sentry.io/4505093974654976
          sentry-cli monitors run cron-job-shell -- bash ${{ github.workspace }}/cron-job.sh
